[2025-01-08T11:38:33.941+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T11:38:33.962+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_dependency_airbyte_dag.test_sources_caches scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-01-08T11:38:33.974+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_dependency_airbyte_dag.test_sources_caches scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-01-08T11:38:33.974+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-08T11:38:34.054+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): test_sources_caches> on 2024-03-07 00:00:00+00:00
[2025-01-08T11:38:34.062+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9154) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-08T11:38:34.063+0000] {standard_task_runner.py:72} INFO - Started process 9160 to run task
[2025-01-08T11:38:34.062+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'task_dependency_airbyte_dag', 'test_sources_caches', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '189', '--raw', '--subdir', 'DAGS_FOLDER/test_airbyte.py', '--cfg-path', '/tmp/tmpp1fbgnl_']
[2025-01-08T11:38:34.064+0000] {standard_task_runner.py:105} INFO - Job 189: Subtask test_sources_caches
[2025-01-08T11:38:34.116+0000] {task_command.py:467} INFO - Running <TaskInstance: task_dependency_airbyte_dag.test_sources_caches scheduled__2024-03-07T00:00:00+00:00 [running]> on host 835c07788e84
[2025-01-08T11:38:34.201+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task_dependency_airbyte_dag' AIRFLOW_CTX_TASK_ID='test_sources_caches' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-01-08T11:38:34.202+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T11:38:34.224+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-01-08T11:38:34.225+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvpi1t1m_z --python=python3.10
[2025-01-08T11:38:34.226+0000] {process_utils.py:190} INFO - Output:
[2025-01-08T11:38:35.258+0000] {process_utils.py:194} INFO - RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.10'
[2025-01-08T11:38:35.310+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 868, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 105, in prepare_virtualenv
    execute_in_subprocess(virtualenv_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/home/airflow/.local/bin/python', '-m', 'virtualenv', '/tmp/venvpi1t1m_z', '--python=python3.10']' returned non-zero exit status 1.
[2025-01-08T11:38:35.325+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=task_dependency_airbyte_dag, task_id=test_sources_caches, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250108T113833, end_date=20250108T113835
[2025-01-08T11:38:35.382+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T11:38:35.383+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 189 for task test_sources_caches (Command '['/home/airflow/.local/bin/python', '-m', 'virtualenv', '/tmp/venvpi1t1m_z', '--python=python3.10']' returned non-zero exit status 1.; 9160)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 868, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 105, in prepare_virtualenv
    execute_in_subprocess(virtualenv_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/home/airflow/.local/bin/python', '-m', 'virtualenv', '/tmp/venvpi1t1m_z', '--python=python3.10']' returned non-zero exit status 1.
[2025-01-08T11:38:35.444+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-08T11:38:35.491+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T11:38:35.499+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-08T12:01:17.913+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-08T12:01:17.933+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: task_dependency_airbyte_dag.test_sources_caches scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-01-08T12:01:17.942+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: task_dependency_airbyte_dag.test_sources_caches scheduled__2024-03-07T00:00:00+00:00 [queued]>
[2025-01-08T12:01:17.943+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-08T12:01:17.995+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonVirtualenvOperator): test_sources_caches> on 2024-03-07 00:00:00+00:00
[2025-01-08T12:01:18.003+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10450) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-08T12:01:18.004+0000] {standard_task_runner.py:72} INFO - Started process 10456 to run task
[2025-01-08T12:01:18.009+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'task_dependency_airbyte_dag', 'test_sources_caches', 'scheduled__2024-03-07T00:00:00+00:00', '--job-id', '331', '--raw', '--subdir', 'DAGS_FOLDER/test_airbyte.py', '--cfg-path', '/tmp/tmpvtlsv2w6']
[2025-01-08T12:01:18.011+0000] {standard_task_runner.py:105} INFO - Job 331: Subtask test_sources_caches
[2025-01-08T12:01:18.059+0000] {task_command.py:467} INFO - Running <TaskInstance: task_dependency_airbyte_dag.test_sources_caches scheduled__2024-03-07T00:00:00+00:00 [running]> on host 835c07788e84
[2025-01-08T12:01:18.153+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='task_dependency_airbyte_dag' AIRFLOW_CTX_TASK_ID='test_sources_caches' AIRFLOW_CTX_EXECUTION_DATE='2024-03-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-07T00:00:00+00:00'
[2025-01-08T12:01:18.154+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-08T12:01:18.178+0000] {baseoperator.py:421} WARNING - PythonVirtualenvOperator.execute cannot be called outside TaskInstance!
[2025-01-08T12:01:18.179+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvoo3hlvaf --python=python3.10
[2025-01-08T12:01:18.181+0000] {process_utils.py:190} INFO - Output:
[2025-01-08T12:01:19.262+0000] {process_utils.py:194} INFO - RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.10'
[2025-01-08T12:01:19.312+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 868, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 105, in prepare_virtualenv
    execute_in_subprocess(virtualenv_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/home/airflow/.local/bin/python', '-m', 'virtualenv', '/tmp/venvoo3hlvaf', '--python=python3.10']' returned non-zero exit status 1.
[2025-01-08T12:01:19.326+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=task_dependency_airbyte_dag, task_id=test_sources_caches, run_id=scheduled__2024-03-07T00:00:00+00:00, execution_date=20240307T000000, start_date=20250108T120117, end_date=20250108T120119
[2025-01-08T12:01:19.359+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-08T12:01:19.360+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 331 for task test_sources_caches (Command '['/home/airflow/.local/bin/python', '-m', 'virtualenv', '/tmp/venvoo3hlvaf', '--python=python3.10']' returned non-zero exit status 1.; 10456)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 505, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 868, in execute_callable
    self._prepare_venv(tmp_path)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 769, in _prepare_venv
    prepare_virtualenv(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/python_virtualenv.py", line 105, in prepare_virtualenv
    execute_in_subprocess(virtualenv_cmd)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 175, in execute_in_subprocess
    execute_in_subprocess_with_kwargs(cmd, cwd=cwd, env=env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/process_utils.py", line 198, in execute_in_subprocess_with_kwargs
    raise subprocess.CalledProcessError(exit_code, cmd)
subprocess.CalledProcessError: Command '['/home/airflow/.local/bin/python', '-m', 'virtualenv', '/tmp/venvoo3hlvaf', '--python=python3.10']' returned non-zero exit status 1.
[2025-01-08T12:01:19.391+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-08T12:01:19.421+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-08T12:01:19.428+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
